language: go
go:
- 1.6
- tip
install:
- go get github.com/stretchr/testify/assert
- go get github.com/leekchan/gtf
- go get github.com/biztos/testig
- go get golang.org/x/text/unicode/norm
- go get github.com/mattn/goveralls
script:
- go test -v -covermode=count -coverprofile=coverage.out
- $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out
  -service=travis-ci -repotoken=$COVERALLS_TOKEN
env:
  global:
    secure: H2BbFXXxfK3vuaRVlbEpkzAuR/5yVRNyJz4JTBDTK3Cljj5fEHZ9Gf2mFvCQirBD+0VqfZvv24nOepJW0W74t/CfWmm7BGVqAoBPEmHeGzdzmh8uoCOgZ5U/8Kyy0ygr2qBs/4/VC5uFRVukK1Vn5RT3bGwAsaw9Zry5Vi6nZSTk2JgmzeStjV+UoDEShzBgk9sE/ElasPRIce1P1nCkNX0zfzwKGxYqU9lk4YU/SNgkiKGEtXiq6Cs/EH4WRwxqYgXFglgZ1zCq8U1nHu+GsS9deeKmeNtjdLnsIVuGDxTVJF+Oe5FpvYII39m/f4pLSkVznNilg/gGzZBY6wnMpAambdvWe8/fyrO//WWL6BBcRVsfkjymVArr7HuUe30ZdDn+lbph0aGoHiHHALzyRFIz8ZFkOHHsC3yqFT9Af8eprk8TMdDB8Hksz0+AHTIuwUEHkkil46hsAAr/VKbQpOj35TZda9PZsGEi9n2yY9/PBl737rxoNzkwVT/zsSv4q3FggYMJt7tEKrXfZ/J/yYvbunwd8ARb/i3qA6sKs0Ir40lVH31GZ7FP4IclRVNC65W9FIXCIEiYohMFKw0Vs+UG/iNfFFYUWOVwN0vWC61PuzPX75YlZ8VjW1Khtp7M5wW8YLiM0Yki0Vonsb68mXrLIP7Texrep94PwWSikfI=
