# This workflow will build a golang project and send the report to coveralls
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Vebben CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test with Coverage
      run: go test -v -coverprofile=cover.out ./...

    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out
